languageCode = "en-us"
title = "Aerial"
baseurl = "https://lubob.net/"
theme = "aerial"

[params]
  name = "Lucius Bobikiewicz"
  about = "Agile Change Manager &nbsp;&bull;&nbsp; Bitcoin Enthusiast &nbsp;&bull;&nbsp; Entrepreneur"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "vv"
  favicon = "favicon.ico"


[[params.social]]
  medium = "Telegram"
  icon = "telegram"
  link = "https://t.me/lubobde"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:lucius.bobikiewicz@lubob.net"
