baseURL = ""
languageCode = "en"
defaultContentLanguage = "en"
title = "Lucius Bobikiewicz"
theme = "stip"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Lucius Bobikiewicz"
    bio = "Agile Change Manager, Entrepreneur, Bitcoin Enthusiast"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:lucius.bobikiewicz@lubob.net"

      